apiVersion: v1
kind: Service
metadata:
    name: "chcluster-cc07"
    labels:
        app: "chcluster-cc07"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "chcluster-cc07"