on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: chregistry1.azurecr.io
        username: ${{ secrets.acr_chregistry1_username }}
        password: ${{ secrets.acr_chregistry1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.github/actions/mkdocs" -f  ".github/actions/mkdocs/Dockerfile" -t chregistry1.azurecr.io/chcluster:${{ github.sha }} --label dockerfile-path=.github/actions/mkdocs/Dockerfile
        docker push chregistry1.azurecr.io/chcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_chcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ch-clustera6f0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ch-clustera6f0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ch-clustera6f0
        container-registry-url: chregistry1.azurecr.io
        container-registry-username: ${{ secrets.acr_chregistry1_username }}
        container-registry-password: ${{ secrets.acr_chregistry1_password }}
        secret-name: chclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ch-clustera6f0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          chregistry1.azurecr.io/chcluster:${{ github.sha }}
        imagepullsecrets: |
          chclusterdockerauth
